### ISSUE TITLE
http://127.0.0.0:5000 does not work

### ISSUE THREAD

**Issue by szutt** [onyxframework/docs#2]
Hello, on https://docs.onyxframework.org/getting-started.html `curl http://127.0.0.0:5000` does not work nor `curl http://127.0.0.1:5000` but `curl http://localhost:5000` does.

Maybe it's because of my environnement (Devuan Ascii 2 x64 inside virtualbox).

**Comment by vladfaust** [comment]
~~Um... Do you see `I, [12:34:56.332] Onyx::REST is listening at http://127.0.0.0:5000` in your terminal? If so, then it is some kind of OS issue, as the server binds to `localhost` by default. As a workaround, you can do `Onyx.listen(host: "0.0.0.0")`, which would bind it to `0.0.0.0` instead.~~

Edit: I'm sorry, I've misread it. Yes, it is because of your environment. I honestly don't know how it is processed internally between OSes, but on Ubuntu `localhost` equals to `127.0.0.1`, and the server is bound to `localhost` by default: https://github.com/onyxframework/onyx/blob/master/src/onyx/http.cr#L46

**Comment by szutt** [comment]
This is the output: at startup:
```
INFO [16:30:27.354 #4252] ⬛ Onyx::HTTP::Server is listening at http://[::1]:5000
```
This is my /etc/hosts
```
127.0.0.1       localhost
127.0.1.1       devuan

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
And the result:
```
$ curl http://127.0.0.0:5000
curl: (7) Couldn't connect to server

$ curl http://127.0.0.1:5000
curl: (7) Failed to connect to 127.0.0.1 port 5000: Connection refused

$ curl http://localhost:5000
Hello, Onyx!
```
And then
```
INFO [16:31:45.197 #4252] [c682ceab]    GET / 200 86μs
```

**Comment by szutt** [comment]
Okay thank you ! I will close this issue. But maybe that should appear on the documentation :-)

**Comment by vladfaust** [comment]
Yes, I will add that to the docs, thanks :heart:
